import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownRight, ArrowUpRight, Plus, WalletCards, X, Trash2 } from 'lucide-react';
import { decryptPayload } from '@zerotracker/core/crypto';
import type { EncryptedExpense } from '@zerotracker/core/db';
import { useAuth } from '../context/AuthContext';
import { StorageMode, useStorage } from '../context/StorageContext';

type PlainExpense = { id: string; amount: number; description: string; income: boolean; date: string; category: string };
const categories = ['Food', 'Rent', 'Salary', 'Utilities', 'Entertainment', 'Custom'];
const money = new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' });
async function decryptRecord(expense: EncryptedExpense, key: CryptoKey): Promise<PlainExpense> { try { const payload = JSON.parse(await decryptPayload(expense.encryptedAmount, expense.iv, expense.authTag, key)) as { amount?: number; income?: boolean; description?: string }; return { id: expense.id, amount: Number(payload.amount ?? 0), income: Boolean(payload.income), description: payload.description ?? '', date: expense.date, category: expense.categoryId ?? 'Uncategorized' }; } catch { return { id: expense.id, amount: 0, income: false, description: 'Encrypted record unavailable', date: expense.date, category: expense.categoryId ?? 'Uncategorized' }; } }

export function DashboardScreen() {
  const { user, masterKey } = useAuth();
  const { mode, getExpenses, addExpense, deleteExpense } = useStorage();
  const [expenses, setExpenses] = useState<PlainExpense[]>([]);
  const [theme, setTheme] = useState(() => localStorage.getItem('zt_theme') ?? 'dark');
  const [isModalOpen, setIsModalOpen] = useState(false); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ amount: '', type: 'expense', category: 'Food', description: '', date: new Date().toISOString().slice(0, 10) });
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('zt_theme', theme); }, [theme]);
  const refresh = useCallback(async () => { if (!user || !masterKey) return; const rows = await getExpenses(); setExpenses(await Promise.all(rows.map((row) => decryptRecord(row, masterKey)))); }, [getExpenses, masterKey, user]);
  useEffect(() => { void refresh().catch(() => setError('Unable to load encrypted records.')); }, [refresh]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!masterKey || !user || Number(form.amount) <= 0) return; setIsSaving(true); setError(''); try { await addExpense({ amount: Number(form.amount), income: form.type === 'income', description: form.description.trim(), categoryId: form.category, date: form.date }); setForm({ amount: '', type: 'expense', category: 'Food', description: '', date: new Date().toISOString().slice(0, 10) }); setIsModalOpen(false); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save transaction.'); } finally { setIsSaving(false); } }
  async function remove(id: string) { try { await deleteExpense(id); await refresh(); } catch { setError('Unable to delete transaction.'); } }
  const income = useMemo(() => expenses.filter((item) => item.income).reduce((sum, item) => sum + item.amount, 0), [expenses]); const spending = useMemo(() => expenses.filter((item) => !item.income).reduce((sum, item) => sum + item.amount, 0), [expenses]);
  return <main className="min-h-screen bg-base-200 px-4 py-8 sm:px-6"><div className="mx-auto max-w-6xl"><header className="navbar mb-6 rounded-box bg-base-100 shadow-sm"><div className="flex-1"><div><p className="text-sm text-primary">Welcome back, {user?.isGuest ? 'Guest' : user?.email}</p><h1 className="text-2xl font-bold sm:text-3xl">Financial overview</h1></div></div><div className="flex items-center gap-2"><span className="badge badge-primary badge-outline hidden sm:inline-flex">{mode === StorageMode.LOCAL_ONLY ? 'LOCAL ONLY' : mode}</span><select aria-label="Theme" value={theme} onChange={(event) => setTheme(event.target.value)} className="select select-bordered select-sm"><option value="dark">Dark</option><option value="emerald">Emerald</option><option value="night">Night</option></select><button onClick={() => setIsModalOpen(true)} className="btn btn-primary btn-sm sm:btn-md"><Plus size={18} />Add</button></div></header>
    <div className="mb-6 flex items-center gap-2"><span className="badge badge-success">●</span><span className="text-sm text-base-content/70">{mode === StorageMode.LOCAL_ONLY ? 'Local-only mode • data never syncs to the cloud' : `Storage mode: ${mode}`}</span></div>{error && <div role="alert" className="alert alert-error mb-5">{error}</div>}
    <div className="stats stats-vertical mb-8 w-full shadow md:stats-horizontal"><Metric label="Total Spent" value={spending} desc="Expenses" icon={<ArrowDownRight />} /><Metric label="Total Income" value={income} desc="Deposits" icon={<ArrowUpRight />} /><Metric label="Net Balance" value={income - spending} desc="Income minus spending" icon={<WalletCards />} /></div>
    <section className="card overflow-hidden bg-base-100 shadow"><div className="card-body p-0"><div className="flex items-center justify-between border-b border-base-300 px-5 py-4"><h2 className="card-title text-lg">Recent transactions</h2><span className="badge badge-ghost">{expenses.length} total</span></div>{expenses.length === 0 ? <div className="py-16 text-center text-base-content/50">No transactions yet. Add your first one to start tracking.</div> : <div className="overflow-x-auto"><table className="table table-zebra"><thead><tr><th>Description</th><th>Category</th><th>Date</th><th className="text-right">Amount</th><th /></tr></thead><tbody>{[...expenses].sort((a, b) => b.date.localeCompare(a.date)).map((item) => <tr key={item.id}><td className="font-medium">{item.description || item.category}</td><td><span className="badge badge-outline">{item.category}</span></td><td>{item.date}</td><td className={`text-right font-semibold ${item.income ? 'text-success' : ''}`}>{item.income ? '+' : '-'}{money.format(item.amount)}</td><td><button className="btn btn-ghost btn-sm text-error" aria-label="Delete transaction" onClick={() => void remove(item.id)}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>}</div></section>
    {isModalOpen && <div className="modal modal-open" role="dialog" aria-modal="true"><section className="modal-box"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-xl font-bold">Add transaction</h2><p className="text-sm text-base-content/60">Encrypted locally before it is saved.</p></div><button onClick={() => setIsModalOpen(false)} className="btn btn-circle btn-ghost" aria-label="Close"><X size={20} /></button></div><form onSubmit={submit} className="grid gap-4"><Field label="Amount ($)"><input required min="0.01" step="0.01" type="number" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} className="input input-bordered w-full" /></Field><Field label="Type"><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="select select-bordered w-full"><option value="expense">Expense</option><option value="income">Income</option></select></Field><Field label="Category"><select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} className="select select-bordered w-full">{categories.map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Description / Merchant name"><input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="e.g. Neighborhood market" className="input input-bordered w-full" /></Field><Field label="Date"><input required type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} className="input input-bordered w-full" /></Field><button disabled={isSaving} className="btn btn-primary mt-2 w-full">{isSaving ? 'Encrypting…' : 'Save transaction'}</button></form></section></div>}
  </div></main>;
}
function Metric({ label, value, desc, icon }: { label: string; value: number; desc: string; icon: ReactNode }) { return <div className="stat"><div className="stat-figure text-primary">{icon}</div><div className="stat-title">{label}</div><div className="stat-value text-2xl">{money.format(value)}</div><div className="stat-desc">{desc}</div></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="form-control w-full"><span className="label-text">{label}</span>{children}</label>; }
